### ISSUE TITLE
A user navigates to the home page and needs to be able to search for restrooms and see results

### ISSUE THREAD

**Issue by d-paller** [jasekiw/ShameTheThrones#11]

**Comment by jasekiw** [comment]
I am working on this

**Comment by jasekiw** [comment]
add stubbed search with test results.

**Comment by jasekiw** [comment]
Queried the database and threw restrooms into the map. Loads restrooms in current view and will load them when you scroll through the map

**Comment by rluttmeratius** [comment]
Closing this.  It looks good.
