### ISSUE TITLE
A user needs to see an average rating

### ISSUE THREAD

**Issue by rluttmeratius** [jasekiw/ShameTheThrones#19]
We need to work on getting all of our data to and from the database, and averaging all of the ratings for the user.

**Comment by jasekiw** [comment]
backend for this is already complete

**Comment by rluttmeratius** [comment]
That's awesome. We just need to do the view I guess. I was thinking just display it to the left of the rate button on the list.

**Comment by jasekiw** [comment]
taken care of in the map.
